[build]
  publish = "dist/ecommerce/browser"
  command = "ng build --configuration production"

[[plugins]]
  package = "@netlify/plugin-angular-universal"

[[redirects]]
  from = "/*"
  status = 200
  to = "/index.html"
